/**
 * @file apps/backend/src/modules/readers/repositories/ReadersRepository.ts
 * @description Repository for Passage Prisma queries.
 *
 * Clean Architecture: Repository — abstracts Prisma ORM.
 * Services must never touch Prisma directly.
 */

import { prisma } from "../../../shared/infrastructure/database/client.js";
import type { Prisma } from "@prisma/client";
import type { CreatePassageInput, PassageRecord, PassageContent } from "../types/readers.js";

/**
 * Repository for passage persistence.
 */
export class ReadersRepository {
  /**
   * List passages, optionally filtered by HSK level.
   * Ordered by passageIndex ascending.
   */
  async findPassages(hskLevel?: number): Promise<PassageRecord[]> {
    const where: Prisma.PassageWhereInput = {};
    if (hskLevel !== undefined) {
      where.hskLevel = hskLevel;
    }

    const records = await prisma.passage.findMany({
      where,
      orderBy: [{ hskLevel: "asc" }, { passageIndex: "asc" }],
    });

    return records.map(this.toRecord);
  }

  /**
   * Find a single passage by ID.
   */
  async findPassageById(id: string): Promise<PassageRecord | null> {
    const record = await prisma.passage.findUnique({ where: { id } });
    if (!record) return null;
    return this.toRecord(record);
  }

  /**
   * Create a new passage.
   */
  async createPassage(data: CreatePassageInput): Promise<PassageRecord> {
    const record = await prisma.passage.create({
      data: {
        hskLevel: data.hskLevel,
        passageIndex: data.passageIndex,
        title: data.title,
        content: data.content as unknown as Prisma.InputJsonValue,
        wordCount: data.wordCount,
        knownWordRatio: data.knownWordRatio,
        targetHskLevel: data.targetHskLevel,
        generatedById: data.generatedById,
      },
    });
    return this.toRecord(record);
  }

  /**
   * Count passages generated by a specific user.
   */
  async countUserGenerated(userId: string): Promise<number> {
    return prisma.passage.count({
      where: { generatedById: userId },
    });
  }

  /**
   * Count passages generated by a user today (UTC).
   */
  async countUserGeneratedToday(userId: string): Promise<number> {
    const todayStart = new Date();
    todayStart.setUTCHours(0, 0, 0, 0);

    return prisma.passage.count({
      where: {
        generatedById: userId,
        generatedAt: { gte: todayStart },
      },
    });
  }

  /**
   * Increment the access count for a passage.
   */
  async incrementAccessCount(id: string): Promise<void> {
    await prisma.passage.update({
      where: { id },
      data: {
        accessCount: { increment: 1 },
        lastAccessedAt: new Date(),
      },
    });
  }

  /**
   * Get character coverage by HSK level for a user.
   * Returns each HSK level with the ratio of characters studied at confidence >= 0.8.
   */
  async getUserCharacterCoverage(
    userId: string,
  ): Promise<Array<{ hskLevel: number; coverageRatio: number }>> {
    const results = await prisma.$queryRaw<Array<{ hskLevel: number; coverageRatio: number }>>`
      SELECT c."hskLevel",
             CAST(COUNT(cp.id) AS FLOAT) / CAST(COUNT(*) AS FLOAT) as "coverageRatio"
      FROM "Character" c
      LEFT JOIN "CharacterProgress" cp
        ON cp."characterId" = c.id AND cp."userId" = ${userId}
        AND cp.confidence >= 0.8
      WHERE c."hskLevel" IS NOT NULL
      GROUP BY c."hskLevel"
      ORDER BY c."hskLevel"
    `;
    return results;
  }

  /**
   * Get the maximum passageIndex for a given HSK level (for assigning next index).
   */
  async getMaxPassageIndex(hskLevel: number): Promise<number> {
    const result = await prisma.passage.aggregate({
      where: { hskLevel },
      _max: { passageIndex: true },
    });
    return result._max.passageIndex ?? -1;
  }

  /**
   * Map Prisma record to domain type.
   */
  private toRecord(record: {
    id: string;
    hskLevel: number;
    passageIndex: number;
    title: string;
    content: Prisma.JsonValue;
    wordCount: number;
    knownWordRatio: number;
    targetHskLevel: number;
    generatedById: string | null;
    generatedAt: Date;
    accessCount: number;
    lastAccessedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
  }): PassageRecord {
    return {
      id: record.id,
      hskLevel: record.hskLevel,
      passageIndex: record.passageIndex,
      title: record.title,
      content: record.content as unknown as PassageContent,
      wordCount: record.wordCount,
      knownWordRatio: record.knownWordRatio,
      targetHskLevel: record.targetHskLevel,
      generatedById: record.generatedById,
      generatedAt: record.generatedAt,
      accessCount: record.accessCount,
      lastAccessedAt: record.lastAccessedAt,
      createdAt: record.createdAt,
      updatedAt: record.updatedAt,
    };
  }
}
