/**
 * @file apps/frontend/src/features/quiz/types/QuizSessionTypes.ts
 * @description API types for quiz session endpoints
 *
 * Story 15.11 Phase 8: Backend-centric quiz session architecture
 * These types map to backend API contracts for quiz session management.
 * Aligned with type audit: story-15-11-type-audit.md
 *
 * Endpoints covered:
 * - POST /api/v1/quiz/session/start
 * - POST /api/v1/quiz/session/:sessionId/answer
 * - GET /api/v1/quiz/session/:sessionId/summary
 */

import { QuizAnswer } from "./QuizTypes";
import { Badge, MysteryBox } from "../../gamification/types/GamificationTypes";

/**
 * Quiz question from backend session (sanitized, no correct answer)
 */
export type QuizSessionQuestion = {
  id: string;
  wordId: string;
  questionType: "multiple_choice" | "type_pinyin" | "type_character";
  word: {
    id: string;
    simplified: string;
    traditional: string;
    pinyin?: string; // Omitted for type_pinyin questions
    english?: string; // Omitted for multiple_choice questions
  };
  options?: string[]; // Present for multiple_choice questions only
};

/**
 * Response from POST /api/v1/quiz/session/start
 *
 * Supports two response variants:
 * - Standard: New or resumed session with questions
 * - Daily Complete: Already completed quiz today (alreadyCompleted = true)
 */
export type QuizSessionStartResponse = {
  sessionId: string;
  questions: QuizSessionQuestion[];
  currentIndex?: number; // Present if resuming
  expiresAt: string; // ISO 8601 datetime
  isResume: boolean; // True if resuming existing session
  answers?: QuizAnswer[]; // Previous answers (only present when isResume = true)
  // Daily quiz variant fields (populated when alreadyCompleted = true)
  alreadyCompleted?: boolean; // True if user already completed quiz today
  // No due words variant (Flow 1.5)
  noDueWords?: boolean; // True when no words due today (backend may return review fallback)
  message?: string; // User-friendly message (e.g. "All caught up! Here are some review words.")
};

/**
 * Request payload for POST /api/v1/quiz/session/:sessionId/answer
 */
export type QuizAnswerRequest = {
  questionId: string;
  userAnswer: string;
  timeSpentMs: number;
};

/**
 * Response from POST /api/v1/quiz/session/:sessionId/answer
 * Story 15.11 Phase 9: AI feedback auto-generated by backend
 * Aligned with type audit: uses nextReviewDate (not nextReview), includes currentStreak
 */
export type QuizAnswerResponse = {
  correct: boolean;
  correctAnswer: string;
  // Progress updates
  nextReviewDate: string; // ISO 8601 datetime (backend property name)
  lapseCount: number;
  isLeech: boolean;
  // Gamification (only present when sessionComplete = true)
  gamification: {
    xpEarned: number;
    newBadges: Badge[];
    mysteryBox: MysteryBox | null; // Nullable per backend spec
    freezeAwarded: boolean;
    currentStreak: number; // Current streak count (backend property)
  } | null;
  // AI feedback (only present when incorrect)
  aiFeedback: {
    explanation: string;
    errorType: "tone" | "character" | "meaning" | "generic";
  } | null;
  // Session state
  nextQuestion: QuizSessionQuestion | null;
  sessionComplete: boolean;
  progress: {
    current: number;
    total: number;
  };
};

/**
 * Incorrect word detail in session summary
 */
export type IncorrectWordDetail = {
  wordId: string;
  hanzi: string;
  pinyin: string;
  english: string;
  userAnswer: string;
  correctAnswer: string;
  questionType: "multiple_choice" | "type_pinyin" | "type_character";
  lapseCount: number;
  isLeech: boolean;
};

/**
 * Per-answer detail from QuizSessionAnswer table (Option 2 refactor)
 * Includes both correct and incorrect answers for the full ResultsTable
 */
export type SessionAnswerDetail = {
  wordId: string;
  hanzi: string;
  pinyin: string;
  english: string;
  questionType: "multiple_choice" | "type_pinyin" | "type_character" | string;
  userAnswer: string;
  correct: boolean;
  correctAnswer: string;
  lapseCount: number;
  isLeech: boolean;
  nextReviewDate: string | null;
};

/**
 * Leech word detail in session summary
 */
export type LeechWordDetail = {
  wordId: string;
  hanzi: string;
  pinyin: string;
  english: string;
  lapseCount: number;
};

/**
 * Response from GET /api/v1/quiz/session/:sessionId/summary
 * Story 15.11: Backend-calculated session metrics
 * Aligned with type audit: uses totalQuestions (not totalAnswered), includes all gamification fields
 */
export type QuizSessionSummary = {
  sessionId: string;
  accuracyRate: number; // 0-100 percentage
  correctCount: number;
  incorrectCount: number; // Backend provides (derived field)
  totalQuestions: number; // Backend property name (not totalAnswered)
  incorrectWords: IncorrectWordDetail[];
  allAnswers: SessionAnswerDetail[]; // All answers (correct + incorrect) for full ResultsTable
  leechWords: LeechWordDetail[];
  leechCount: number; // Backend provides (derived field)
  leechWordIds: string[]; // Backend provides (derived field)
  // Gamification data (from completed session)
  xpEarned: number; // Backend property name (not totalXP)
  newBadges: Badge[];
  mysteryBox: MysteryBox | null;
  freezeAwarded: boolean;
  currentStreak: number;
  availableFreezes: number;
};
