name: Storybook Checks

on:
  pull_request:
    branches: [main]

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build-storybook --workspace=@mandarin/frontend
      - run: npm run lint:css --workspace=@mandarin/frontend
